@Book_manager_HostAddress = http://localhost:5034

### POST /Api/Books

POST {{Book_manager_HostAddress}}/Api/Books
Accept: application/json
Content-Type: application/json

{
  "name": "Dom Casmurro",
  "author": "Machado de Assis",
  "imageUrl": "https://example.com/domcasmurro.jpg",
  "rating": 5,
  "status": 3,
  "description": "Um clássico da literatura brasileira."
}

###